import Head from "next/head";
import styles from "../styles/Home.module.css";
import Accordion from "react-bootstrap/Accordion";
import Veggie from "../components/Veggie";
import Popular from "../components/Popular";
import Category from "../components/Category";

import Image from "next/image";
import { Container } from "react-bootstrap";
import Nordic from "../components/Nordic";

export default function Home() {
  return (
    <>
      <Head>
        <title>Recipes Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Category></Category>

      {/* <Accordion defaultActiveKey={["0"]} alwaysOpen bsPrefix>
        <Accordion.Item eventKey="0">
          <Accordion.Header>Veggie Picks</Accordion.Header>
          <Accordion.Body>
            <Veggie />
          </Accordion.Body>
        </Accordion.Item>

        <Accordion.Item eventKey="1">
          <Accordion.Header>Popular Picks</Accordion.Header>
          <Accordion.Body>
            <Popular />
          </Accordion.Body>
        </Accordion.Item>

        <Accordion.Item eventKey="2">
          <Accordion.Header>Nordic Picks</Accordion.Header>
          <Accordion.Body>
            <Nordic />
          </Accordion.Body>
        </Accordion.Item>
      </Accordion> */}

      <Veggie></Veggie>

      <Popular></Popular>

      <Nordic></Nordic>
    </>
  );
}
