import Head from "next/head";
import styles from "../styles/Home.module.css";

import Veggie from "../components/Veggie";
import Popular from "../components/Popular";
import Category from "../components/Category";

import Image from "next/image";
import { Container } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Container fluid>
        <Container fluid>
          <Head>
            <title>Recipes Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </Container>

        <Category></Category>

        <Veggie></Veggie>

        <Popular></Popular>
      </Container>
    </>
  );
}
